add example code use_two_plugins
wechaty/python-wechaty-plugin-contrib pull request #11
Opened 2021-10-07 12:16 UTC by xinyu3ru

* add example code use_two_plugins.
* update README.MD file.

2021-10-07 12:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/wechaty/python-wechaty-plugin-contrib?pullRequest=11) <br/>All committers have signed the CLA.

2021-10-08 02:11 UTC, wj-Mcat requested changes
Thank for your improvement about the plugin module. Plase read my comment to fix mistakes.

2021-10-08 02:11 UTC, wj-Mcat commented on README.md
> +| 12 | Use_two_plugins | [@xinyu3ru](https://github.com/xinyu3ru) | Example code How to use two or more plugins. |
How did you get the author of this plugin ?  There are many mistake in author column.  Please correct it.

2021-10-08 02:11 UTC, wj-Mcat commented on README.md
> +Example code in examples folder, [use_two_plugins](https://github.com/wechaty/python-wechaty-plugin-contrib/blob/master/examples/use_two_plugins.py)
Please get the author of plugin from the pull request or forced commit. Or you can see the history of plugin file not the example code file.

2021-10-08 02:11 UTC, wj-Mcat commented on README.md
> +- @markoxu - [@markoxu](https://github.com/markoxu), Software Development Engineer at Intel Corporation.
`markoxu` is the contributor not the maintainer.  Please remove it from the docs.

2021-10-08 02:11 UTC, wj-Mcat commented on examples/use_two_plugins.py
> +        self.login_user = contact
we should mainly add the plugin usage code not the usages of wechaty interface.  Please remove it and add more plugin example code.

2021-10-08 13:24 UTC, xinyu3ru commented on examples/use_two_plugins.py
> +        self.login_user = contact
I removed this file.

2021-10-08 13:25 UTC, xinyu3ru commented on README.md
> +- @markoxu - [@markoxu](https://github.com/markoxu), Software Development Engineer at Intel Corporation.
I corrected the maintainer and contributer.

2021-10-08 13:25 UTC, xinyu3ru commented on README.md
> +Example code in examples folder, [use_two_plugins](https://github.com/wechaty/python-wechaty-plugin-contrib/blob/master/examples/use_two_plugins.py)
pls check my new pull request.

2022-04-20 07:06 UTC, wj-Mcat commented
@xinyu3ru there are some conflict errors in the `README.md` file, please fix it later. Looking forward for your great next work.

2023-12-29 14:13 UTC, closed without merging